name: Lint and Test

on:
  pull_request:

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js 18.18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.x'
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: TS Check
        run: yarn ts:check
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
